name: CI

on:
  pull_request:
    branches: [ main, development ]
  push:
    branches: [ main, development ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run npm install and build
        run: |
          npm install
          npm run build

      - name: Run tests
        run: npm run test
